// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    fare_distribution: {
        name: "fare_distribution";
        parameters: {
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          fare_bucket: string;
          /** @sqlType BIGINT */
          trip_count: number;
        }>;
      };
    kpi_summary: {
        name: "kpi_summary";
        parameters: {
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          avg_fare: number;
          /** @sqlType DOUBLE */
          total_fare: number;
          /** @sqlType DOUBLE */
          avg_distance: number;
          /** @sqlType DOUBLE */
          avg_duration_min: number;
        }>;
      };
    top_routes: {
        name: "top_routes";
        parameters: {
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType INT */
          pickup_zip: number;
          /** @sqlType INT */
          dropoff_zip: number;
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          avg_fare: number;
          /** @sqlType DOUBLE */
          avg_distance: number;
        }>;
      };
    trips_by_day: {
        name: "trips_by_day";
        parameters: {
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          trip_date: string;
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          avg_fare: number;
        }>;
      };
    trips_by_hour: {
        name: "trips_by_hour";
        parameters: {
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType INT */
          pickup_hour: number;
          /** @sqlType BIGINT */
          trip_count: number;
        }>;
      };
  }
}
